dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install -g codecov
  - npm install coveralls
  - npm install local-backend
  - npm install

before_script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

script:
  - codecov
  - node ./node_modules/protractor/bin/webdriver-manager update --versions.chrome 79.0.3945.88

after_script:
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
